services:
  apitestpostgresql:
    image: ${DOCKER_REGISTRY-}apitestpostgresql
    build:
      context: .
      dockerfile: ApiTestPostgreSQL/Dockerfile
    networks:
      - apitestpostgres
    depends_on:
      db:
        condition: service_healthy
        restart: true
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - apitestpostgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: 
networks:
  apitestpostgres: