services:
  apitestpostgresql:
    image: ${DOCKER_REGISTRY-}apitestpostgresql
    build:
      context: .
      dockerfile: ApiTestPostgreSQL/Dockerfile
    networks:
      - apitestpostgres
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - apitestpostgres
    expose:
      - 5432
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: 
networks:
  apitestpostgres: