services:
  graphqlserver:
    image: ${DOCKER_REGISTRY-}graphqlserver
    build:
      context: .
      dockerfile: HotChocolate/Dockerfile
    ports:
      - "5270:8080"
      - "7296:8081"

  apollo-router:
    # image: ghcr.io/apollographql/router:v1.61.0
    #command: router --config router-config.yaml
    image: ${DOCKER_REGISTRY-}router
    build:
      context: .
      dockerfile: Router/Dockerfile
    ports:
      - "4000:4000"
    env_file: Router/.env

  apollo-rover:
    image: ${DOCKER_REGISTRY-}rover
    build:
      context: .
      dockerfile: Rover/Dockerfile
    ports:
      - "4200:4200"
    env_file: Rover/.env
    command: dev --supergraph-config Rover/supergraph-config.yaml