services:
  graphqlserver:
    image: ${DOCKER_REGISTRY-}graphqlserver
    build:
      context: .
      dockerfile: HotChocolate/Dockerfile
    ports:
      - "5270:8080"
      - "7296:8081"

  apollo-rover:
    image: ${DOCKER_REGISTRY-}rover
    build:
      context: .
      dockerfile: Rover/Dockerfile
    ports:
      - "4200:4200"
    env_file: Rover/.env
    # Launching gives this error: "error: Invalid path. No file found at supergraph-config.yaml".
    # More docker research required for building this image correctly
    command: dev --supergraph-config supergraph-config.yaml