services:
  graphqlserver:
    image: ${DOCKER_REGISTRY-}graphqlserver
    build:
      context: .
      dockerfile: HotChocolate/Dockerfile

  apollo-router:
    image: ${DOCKER_REGISTRY-}router
    build:
      context: .
      dockerfile: Router/Dockerfile
    ports:
      - "4000:4000"
    env_file: Router/.env

  apollo-rover:
    image: ${DOCKER_REGISTRY-}rover
    build:
      context: .
      dockerfile: Rover/Dockerfile
    ports:
      - "4200:4200"
    env_file: Rover/.env